server:
  port: 0
  
spring:
  main:
    banner-mode: "off"
  application:
    name: spring-boot-application
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true   
      
      
welcome-message: Welcoem to Spring Boot Microservice      